modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="portalmod"
version="1.2"
displayName="PortalMod"
logoFile="logo.png"
authors="SerialSniper, PhantomEye, LarsMans"
description='''
§7----------------------------------------§r

§lPortal in Minecraft, reimagined.§r

This mod is dedicated to our friend and beloved community member bunnyhall_ (Niko).

§7----------------------------------------§r

§lMAIN TEAM§r
§6SerialSniper - Lead Developer§r
§3PhantomEye - Developer & Artist§r
§2LarsMans - Developer§r

§lCONTRIBUTORS§r
§7Scyriate - Sound Design
13JS - Sound Design
Shugdin - Turret Model
Ultimatech - Concept & Model Artist
Tec - Animated Texture Artist§r

§lEARLY SUPPORTERS§r
§7Izumi, Tijn Swets, hented guitar, Maiden_Walkout, RubiiW, mysmay, Cleetus, Tirnups, Lazercats, scrimbo, Casty, KruF, John Adam, Lemo, DaLumma, InkTube, GalaxyGamer, mcietom, BattleNicolas, BlockRat, Smofacini, Boojusz, CombustLem, Daybroken, SonicNug, NotTouchedGrass, JustNonExistant, TheOnlyBendyy, rick_hampter, BZKgns, pejoe․dev, JajmeLesLjcornes, GLaDOS38, Fusion Flux, WORMSTweaker, Jessie Yun, Redbrid_Candy, Groobler, Fiopon, Andus, ElevenChars, YahBoiBarry, Pixe_GUM, Rick Al, YM_Galaxy, Gek, Norfair00, Night The Fox, MilkyVR, Whykioh, badhaloninja, Mobboss754, Slimebo, LinuxAvali, FuzzyLeo, Tankerous, nozzlewatson, NullPointer, LiamXSage, TardisEngineer, Dimotré, Lassilos, KitsOriK_KOT, Noah_the_cat, anthony2611, Chez0/CheZZero, PolDog, Maxwell Buk, WafWaffie, PortalSans, SomeRandomKevin, polynnemorphism, Emery319, aabourke, disk, Skye, Astronomical_bruh/Kaz8518, Smol LS, Workattack, ronaldxrobu, NinjaJayBird, Mr․Mouse§r

§lPLAYTESTING§r
§7Lemo, WafWaffie, PolkaIDK_, Tec, Charaster, hented guitar, Nuxandar, RedBrid_Candy, Freeguy, Andrew_222, GalaxyGamer, DaLumma, MrCube6, S0NIC130, RubiiW, NullPointer, curryducker, Finchy, Cleetus, Grac3_bunni, TardisEngineer, rick_hampter, Scyriate§r

§lINTERNATIONALIZATION§r
§7Brazilian Portuguese: matwo, zYuu, Nilbaldis, Jv2211, KyomaH, Matsilagi, EoDantez, Zé Granola
European Portuguese: FlannPud, Ghost_AVO
German: CRUGG, Laura Sofia Heimann, ModLabs․CC, Cobyte, IkeaDome
Turkish: AYBERK-DINCSOY, Bulut Mete, Vertex, TunedWolf, SomeCherryDude/MrCherry09, TheBoozled
European Spanish: MissingNo Polaris, Neolux7z, Tocinin, Yo_oficial
Mexican Spanish: Fishysalmon02
LOLCAT: Neolux7z, S0NIC130, Wanneshey, Andus, PolkaIDK_
Traditional Chinese: yhr_C
Simplified Chinese: yhr_C
French: Garatim, Kobrha, Lumaa, Whykioh, WORMSTweaker, Julien MACHADO/PhobosRandom, RubiiW, JajmeLesLjcornes
Ukrainian: NdrNmnk, TheWrlQ, hented guitar, KitsoriK KOT
Hungarian: NotFoowa, Boojusz
Latin: puppypolymathy
toki pona: puppypolymathy, LarsMans, jan Situpi
Russian: Yodar de von Wizel, PolkaIDK_, Unitei, MR_Vintyx
Slovak: Slovak Shadow
Czech: Slovak Shadow, Stepanek740
Polish: yagoonek, Chrzanek, Andus, bunnyhall_, Callie, ender24
Dutch: Charaster, Wanneshey, pejoe․dev, Max van den Berg, PhantomEye, Tijn Swets, LarsMans
Italian: Sparkyy, teho_, IlG1ann1, SerialSniper
Finnish: Osmis10
Danish: DiceHeadOstrich, Pikkachau
Thai: Aikoyori
Korean: MAWE_MAWE, UNS_Online
Japanese: simi_OwO
Welsh: amethyst2667
Swedish: FOrt404
Pirate Speak: Thetrueredtiger§r

§lSPECIAL THANKS§r
§7Krzyhau - Source Engine Insight
Nuxandar - Portal Assistance
Valve - Creating Portal
You - For playing!§r
'''