modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="portalmod"
version="0.3.1"
displayName="PortalMod"
#logoFile="examplemod.png"
authors="SerialSniper, PhantomEye, LarsMans"
description='''
Portal in Minecraft, reimagined.
'''