name: Bug Report
description: Report a bug / issue
labels: ["bug"]
type: Bug
body:
  - type: input
    attributes:
      label: What version of the mod are you using?
      placeholder: "1.0"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched [GitHub](https://github.com/snowy-shack/PortalMod/issues?q=sort%3Aupdated-desc%20is%3Aissue) for my bug / issue
          required: true
        - label: I just clicked all the boxes in the checklist
        - label: This is the latest version of the mod
          required: true

  - type: textarea
    attributes:
      label: What happened?
      placeholder: When doing this, that happens
    validations:
      required: true

  - type: textarea
    attributes:
      label: Please upload a video or screenshots showcasing the issue
      placeholder: ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce the bug from a **new world**?
      placeholder: Steps to replicate the issue from a blank world
    validations:
      required: true

  - type: input
    attributes:
      label: What other mods do you have installed?
      placeholder: Optifine, ...
    validations:
      required: true

  - type: input
    attributes:
      label: What's your Operating System?
      placeholder: Windows 10 / MacOS ... / Linux distro ...
    validations:
      required: true

  - type: input
    attributes:
      label: Your latest.log
      description: Please give us a URL to your latest.log (we recommend uploading it to https://mclo.gs/)
      placeholder: https://mclo.gs/<id>
    validations:
      required: true
