name: Bug Report
description: Report a bug / issue
labels: ["bug"]
type: Bug
body:
  - type: markdown
    attributes:
      value: "# Bug / issue Report"

  - type: checkboxes
    attributes:
      label: Latest Version
      options:
        - label: I am running the latest version of the mod.
          required: true

  - type: textarea
    attributes:
      label: What happened?
      placeholder: When doing this, that happens
    validations:
      required: true

  - type: textarea
    attributes:
      label: Video / screenshots
      placeholder: Please upload a video or screenshots showcasing the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce the bug?
      placeholder: Steps to replicate the issue from a blank world
    validations:
      required: true

  - type: input
    attributes:
      label: What version of the mod are you using?
      placeholder: "1.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Your latest.log
      description: Please give us a URL to your latest.log (we recommend uploading it to https://gist.github.com/)
      placeholder: https://gist.github.com/<user>/<gist id>