name: Suggestion
description: Suggest a new feature
title: "Suggestion: "
type: Feature
body:
  - type: markdown
    attributes:
      value: "# Suggestion"

  - type: textarea
    attributes:
      label: What is your suggestion?
      placeholder: Release Portal 3