from PIL import Image
import os

#
# CODE GENERATED BY CHATGPT CAUSE I COULDNT BE ARSED TO WRITE THIS
#

# Load the 96x96 pixel art texture
original_path = "chamber_door_map.png"
texture = Image.open(original_path)

# Get the directory of the original file
output_dir = os.path.dirname(original_path)

# Parameters for slicing
cell_size = 16
grid_size = 6  # 6x6 grid for 96x96 image

# List of custom names for each texture (indices 0 to 15)
output_names = [
    "chamber_door_frame_top.png",
    "chamber_door_frame_inside_ceiling.png",
    "chamber_door_middle_top_sign.png",
    "chamber_door_frame_inside_top.png",
    "chamber_door_side_top.png",
    "chamber_door_side_top_sign.png",
    "chamber_door_frame_side_top.png",
    "chamber_door_middle_top.png",
    "chamber_door_middle_bottom_sign.png",
    "chamber_door_frame_inside_bottom.png",
    "chamber_door_side_bottom.png",
    "chamber_door_side_bottom_sign.png",
    "chamber_door_frame_side_bottom.png",
    "chamber_door_middle_bottom.png",
    "chamber_door_bottom.png",
    "chamber_door_bottom_sign.png"
]

# Loop through each cell in the 6x6 grid
index = 0
for row in range(grid_size):
    for col in range(grid_size):
        if index >= len(output_names):
            break  # Only process up to the length of the specified names list
        
        # Define the bounding box for the 16x16 cell
        left = col * cell_size
        upper = row * cell_size
        right = left + cell_size
        lower = upper + cell_size

        # Crop the cell from the main texture
        cell_image = texture.crop((left, upper, right, lower))
        # Check if the cell is non-empty (not completely transparent or blank)
        if cell_image.getbbox():  # Only save if not empty
            # Save the image in the same directory as the original with the specified name
            output_path = os.path.join(output_dir, output_names[index])
            cell_image.save(output_path)
            print(f"Saved: {output_path}")  # Print confirmation
            index += 1

